// Code generated by protoc-gen-go from "messages.proto"
// DO NOT EDIT!

package messages

import proto "code.google.com/p/goprotobuf/proto"
import "math"

// Reference proto and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type User struct {
	FirstName        *string `protobuf:"bytes,1,req,name=first_name" json:"first_name,omitempty"`
	LastName         *string `protobuf:"bytes,2,req,name=last_name" json:"last_name,omitempty"`
	PostCount        *int64  `protobuf:"varint,3,opt,name=post_count" json:"post_count,omitempty"`
	Friends          []*User `protobuf:"bytes,4,rep,name=friends" json:"friends,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *User) Reset()         { *this = User{} }
func (this *User) String() string { return proto.CompactTextString(this) }
func (*User) ProtoMessage()       {}

func (this *User) GetFirstName() string {
	if this != nil && this.FirstName != nil {
		return *this.FirstName
	}
	return ""
}

func (this *User) GetLastName() string {
	if this != nil && this.LastName != nil {
		return *this.LastName
	}
	return ""
}

func (this *User) GetPostCount() int64 {
	if this != nil && this.PostCount != nil {
		return *this.PostCount
	}
	return 0
}

func init() {
}
