### Generated by rprotoc. DO NOT EDIT!
### <proto file: messages/messages.proto>
# package messages;
# 
# message User {
#   required string first_name = 1;
#   required string last_name = 2;
#   optional int64 post_count = 3;
# 
#   repeated User friends = 4;
# }

require 'protobuf/message/message'
require 'protobuf/message/enum'
require 'protobuf/message/service'
require 'protobuf/message/extend'

module Messages
  class User < ::Protobuf::Message
    defined_in __FILE__
    required :string, :first_name, 1
    required :string, :last_name, 2
    optional :int64, :post_count, 3
    repeated :User, :friends, 4
  end
end